apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-v1
  namespace: microservice-v1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: product247.com
      http:
        paths:
          - path: /app/v1(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: springboot-crud-svc-v1
                port:
                  number: 9191
