apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-v1
  namespace: microservice-v1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$3
spec:
  rules:
    - host: product247.com
      http:
        paths:
          - path: "/app/v1/(/|$)(.*)" # use it as http://product247.com/app/v1/<endpoints of apps>
            pathType: ImplementationSpecific
            backend:
              service:
                name: springboot-crud-svc-v1 # name of your app svc # type should be ClusterIP
                port:
                  number: 9191