apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-v2
  namespace: microservice-v2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: product247.com
      http:
        paths:
          - path: "/app/v2(/|$)(.*)"
            pathType: ImplementationSpecific
            backend:
              service:
                name: springboot-crud-svc-v2
                port:
                  number: 9191